# Default values for the crypto-tracker Helm chart

# Global configurations
global:
  imagePullPolicy: IfNotPresent

# Kafka configuration
kafka:
  replicas: 1
  config:
    broker:
      config:
        auto.create.topics.enable: "true"
    zookeeper:
      replicas: 1

# Spark configuration
spark:
  worker:
    replicas: 1
  job:
    image:
      repository: crypto-tracker-spark-job
      tag: latest
    mainApplicationFile: local:///opt/spark-job/spark_job.py

# InfluxDB configuration
influxdb:
  persistence:
    enabled: true
    size: 1Gi
  config:
    http:
      auth-enabled: false
  database: crypto_data

# Data collector app configuration
dataCollector:
  image:
    repository: crypto-tracker-data-collector
    tag: latest
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1"
  kafka:
    broker: kafka-cluster-kafka-bootstrap.kafka:9092
    topic: crypto-data

# Spark job configuration
sparkJob:
  image:
    repository: crypto-tracker-spark-job
    tag: latest
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1"
  kafka:
    broker: kafka-cluster-kafka-bootstrap.kafka:9092
    topic: crypto-data
  influxdb:
    host: influxdb
    port: 8086
    database: crypto_data

# Dashboard app configuration
dashboard:
  image:
    repository: crypto-tracker-dashboard
    tag: latest
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1"
  influxdb:
    host: influxdb
    port: 8086
    database: crypto_data
  service:
    type: ClusterIP
    port: 5000
  ingress:
    enabled: true
    host: crypto-tracker.local

# Network policy configurations (optional)
networkPolicy:
  enabled: false