global:
  namespace: crypto-tracker

# Kafka configuration
strimzi-kafka-operator:
  enabled: true
  name: kafka-cluster
  replicas: 1
  config:
    kafkaVersion: 3.8.0
    zookeeper:
      replicas: 3
  topic:
    name: crypto-data
    config:
      partitions: 1
      replicas: 1

# Spark configuration
spark-operator:
  enabled: true
  name: spark-app
  spark:
    jobNamespaces:
      - crypto-tracker
  controller:
    replicas: 1
    workers: 5
  sparkUIOptions:
    ingressAnnotations:
        kubernetes.io/ingress.class: nginx
  config:
    sparkVersion: 3.5.3
    image: crypto-tracker/spark-py:latest
    mainApplicationFile: local:///opt/spark/work-dir/spark_app.py
    driver:
      cores: 1
      memory: 512m
      serviceAccount: crypto-tracker-spark-operator-spark
    executor:
      instances: 2
      cores: 1
      memory: 512m
    kafka:
      broker: kafka-cluster-kafka-bootstrap:9092
      topic: crypto-data

# InfluxDB v2 configuration
influxdb2:
  enabled: true
  adminUser:
    organization: "crypto-tracker-org"
    bucket: "crypto-tracker-bucket"
    user: "admin"
    retention_policy: "0s"
    password: "admin-password"
    token: "secret-token"