apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: crypto-tracker
type: Opaque
data:
  admin-password: YWRtaW4tcGFzc3dvcmQ= # Base64 value of the password
  admin-token: bXktc2VjcmV0LWluZmx1eGRiLXRva2Vu # Base64 value of the token