apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-user-crypto-tracker
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: kafka-topic-crypto-tracker
          patternType: literal
        operations:
          - Describe
          - Read
          - Write
        host: "*"