---
# Service for Kafka Broker
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka

---
# Service for Spark Job (for inter-component communication)
apiVersion: v1
kind: Service
metadata:
  name: spark-job-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 7077
      targetPort: 7077
      protocol: TCP
  selector:
    app: spark-job

---
# Service for InfluxDB (accessible to dashboard and other components)
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
  selector:
    app: influxdb

---
# Service for Dashboard (can be exposed externally for user access)
apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort  # Change to LoadBalancer if deploying outside Minikube
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30000    # Accessible on Minikube's node IP on port 30000
  selector:
    app: dashboard
