apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.streamlit.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.streamlit.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.streamlit.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.streamlit.name }}
    spec:
      containers:
        - name: streamlit
          image: {{ .Values.streamlit.image }}
          imagePullPolicy: {{ .Values.streamlit.imagePullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: INFLUXDB_URL
              value: http://crypto-tracker-influxdb2.crypto-tracker.svc:8086
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-auth
                  key: admin-token
            - name: INFLUXDB_ORG
              value: crypto-tracker-org
            - name: INFLUXDB_BUCKET
              value: crypto-tracker-bucket